apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: swarmguard-sync-api
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/swarmguard-sync-api
          ports:
            - containerPort: 8080
